### ISSUE TITLE
Why not Aurelia?

### ISSUE THREAD

**Issue by Vheissu** [arguiot/ProType#2]
First of all, kudos for the awesome effort creating ProType, I can tell you have put a lot of effort into this. Under the reasons on your website where you say "why" you say the following:

>Because I couldn't find a framework that could use classes in the most effective way.

Have you heard of Aurelia before? It's a class-based Javascript framework with similar concepts of a view/view-model (aka controller). It's very similar to the problem you were hoping to resolve with ProType: https://aurelia.io/

Just thought I would mention it because I think you would really enjoy it and you might actually get inspiration from its features to add back into ProType as well.

**Comment by arguiot** [comment]
Thank you 😊
